### ISSUE TITLE
Problem while adding resources to container

### ISSUE THREAD

**Issue by noorbakerally** [ldp4j/ldp4j#29]
I am getting an error when adding members to a container:

this code is working completely fine:

```
@Override
	public void initialize(WriteSession session) {
		LOGGER.info("Initializing Application...");
		try {

			ContainerSnapshot containerSnapshot = (ContainerSnapshot)session.find(ResourceSnapshot.class, this.parkingContainerName,ParkingContainerHandler.class);
			containerSnapshot.addMember(NamingScheme.getDefault().name("test1"));
			containerSnapshot.addMember(NamingScheme.getDefault().name("test2"));
			containerSnapshot.addMember(NamingScheme.getDefault().name("test3"));

			
			session.saveChanges();
			LOGGER.info("Application initialization completed.");
		} catch (WriteSessionException e) {
			LOGGER.warn("Application initialization failed.",e);
			throw new IllegalStateException(e);
		}
	}
```

However, just replacing the 3 line for adding members by a loop causes an error:

```
@Override
	public void initialize(WriteSession session) {
		LOGGER.info("Initializing Application...");
		try {

			ContainerSnapshot containerSnapshot = (ContainerSnapshot)session.find(ResourceSnapshot.class, this.parkingContainerName,ParkingContainerHandler.class);

			int i = 0;
			while (i<4){
				String resourceName = "test"+i;
				containerSnapshot.addMember(NamingScheme.getDefault().name(resourceName));
			}

			session.saveChanges();
			LOGGER.info("Application initialization completed.");
		} catch (WriteSessionException e) {
			LOGGER.warn("Application initialization failed.",e);
			throw new IllegalStateException(e);
		}
	}
```

When using a loop to add the members, i'm getting the following error:

```
SEVERE: Exception sending context initialized event to listener instance of class org.ldp4j.server.setup.BootstrapContextListener
java.lang.IllegalStateException: Transient resource should be new
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at org.ldp4j.application.session.DelegatedWriteSession.newTransient(DelegatedWriteSession.java:309)
	at org.ldp4j.application.session.DelegatedResourceSnapshot.newChildResource(DelegatedResourceSnapshot.java:170)
	at org.ldp4j.application.session.PersistencyState$BasePersistencyState.addMember(PersistencyState.java:247)
	at org.ldp4j.application.session.PersistencyState$PersistentResourceState.addMember(PersistencyState.java:369)
	at org.ldp4j.application.session.DelegatedContainerSnapshot.addMember(DelegatedContainerSnapshot.java:76)
	at org.ldp4j.tutorial.frontend.MyApplication.initialize(MyApplication.java:112)
	at org.ldp4j.application.lifecycle.ApplicationLoader.initialize(ApplicationLoader.java:105)
	at org.ldp4j.application.lifecycle.ApplicationLoader.bootstrap(ApplicationLoader.java:98)
```

any idea of how I can solve this problem ?
thanks

**Comment by mestebangutierrez** [comment]
You are missing the index variable increment (`i++`) inside the loop, thus you always attempt to add the very same member. 

If it had not failed because of that exception, it would have exhausted the heap space and failed with an `OutOfMemoryError`.

**Comment by noorbakerally** [comment]
Goodness, frankly, i spent at least 30 mins on this and didn't even see that infinite loop, thanks though !!

**Comment by mestebangutierrez** [comment]
You're welcome. Please close the issue if solved.
